version: '3.7'

services: 
    db:
        image: mariadb:10.4.12
        container_name: mariadb
        restart: always
        volumes: 
            - ./data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
        ports: 
            - 3306:3306